version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: intellimaint
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  gateway:
    build:
      context: ../gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/intellimaint
      REDIS_URL: redis://redis:6379
    depends_on:
      - postgres
      - redis

  orchestrator:
    build:
      context: ../services/orchestrator
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      ENVIRONMENT: development

  vision-service:
    build:
      context: ../services/vision_service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"

  rag-service:
    build:
      context: ../services/rag_service
      dockerfile: Dockerfile
    ports:
      - "8002:8002"

  asr-tts-service:
    build:
      context: ../services/asr_tts_service
      dockerfile: Dockerfile
    ports:
      - "8003:8003"

volumes:
  postgres_data:

